### ISSUE TITLE
[QQAPI&QQchat]: 插件报错

### ISSUE THREAD

**Issue by doubiovo** [AnzhiZhang/MCDReforgedPlugins#101]
[MCDR] [12:04:46] [TaskExecutor/ERROR]: Error invoking listener EventListener[plugin=qq_api@1.1.1,priority=1000,callback=<function on_load at 0x00000217BFE2A790>]
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\mcdreforged\plugin\plugin_manager.py", line 589, in trigger_listener
    listener.execute(listener.plugin.server_interface, *args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\mcdreforged\plugin\plugin_event.py", line 106, in execute
    return self.callback(*args, **kwargs)
  File "plugins\QQAPI-v1.1.1.mcdr\qq_api\__init__.py", line 41, in on_load
    __bot = CQHttp(api_root=f"http://{config.api_host}:{config.api_port}")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiocqhttp\__init__.py", line 135, in __init__
    self._server_app = Quart(import_name, **(server_app_kwargs or {}))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\quart\app.py", line 308, in __init__
    self._first_request_lock = self.lock_class()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\locks.py", line 81, in __init__
    self._loop = events.get_event_loop()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'TaskExecutor'.
[MCDR] [12:04:46] [TaskExecutor/INFO] [qq_chat]: 配置文件已加载
[MCDR] [12:04:46] [TaskExecutor/ERROR]: Error invoking listener EventListener[plugin=qq_chat@1.0.0,priority=1000,callback=<function on_load at 0x00000217C0844550>]
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\mcdreforged\plugin\plugin_manager.py", line 589, in trigger_listener
    listener.execute(listener.plugin.server_interface, *args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\mcdreforged\plugin\plugin_event.py", line 106, in execute
    return self.callback(*args, **kwargs)
  File "plugins\QQChat-v1.0.0.mcdr\qq_chat\__init__.py", line 68, in on_load
    final_bot = server.get_plugin_instance('qq_api').get_bot()
  File "plugins\QQAPI-v1.1.1.mcdr\qq_api\__init__.py", line 106, in get_bot
    return __bot
NameError: name '__bot' is not defined
[MCDR] [12:05:03] [TaskExecutor/ERROR]: Error invoking listener EventListener[plugin=qq_chat@1.0.0,priority=1000,callba]
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\mcdreforged\plugin\plugin_managr
    listener.execute(listener.plugin.server_interface, *args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\mcdreforged\plugin\plugin_evente
    return self.callback(*args, **kwargs)
  File "plugins\QQChat-v1.0.0.mcdr\qq_chat\__init__.py", line 88, in on_server_startup
    send_msg_to_all_groups('Server is started up')
  File "plugins\QQChat-v1.0.0.mcdr\qq_chat\__init__.py", line 270, in send_msg_to_all_groups
    event_loop.run_until_complete(
NameError: name 'event_loop' is not defined
go-cqhttp也报错
[2023-02-18 12:07:11] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试
[2023-02-18 12:07:15] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试
[2023-02-18 12:07:18] [WARNING]: 上报 Event 数据到 http://127.0.0.1:5701/ 失败: Post "http://127.0.0.1:5701/": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试
[2023-02-18 12:07:22] [WARNING]: 上报 Event 数据 {"post_type":"meta_event","meta_event_type":"heartbeat","time":1676693229,"self_id":3537494107,"interval":5000,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":25,"packet_sent":16,"packet_lost":0,"message_received":0,"message_sent":0,"disconnect_times":0,"lost_times":0,"last_message_time":0}}}

**Comment by AnzhiZhang** [comment]
尝试重启，观察是否可复现，请提供一个稳定复现的方式

**Comment by AnzhiZhang** [comment]
It's a problem with the different features of higher versions of asyncio. It has now been made backward compatible with lower version of Python. Please use qq_api@1.2.0 and qq_chat@1.0.1.

https://github.com/AnzhiZhang/MCDReforgedPlugins/releases/tag/qq_api-v1.2.0
https://github.com/AnzhiZhang/MCDReforgedPlugins/releases/tag/qq_chat-v1.0.1
