### ISSUE TITLE
Bot-v1.1.5 get_location ERROR

### ISSUE THREAD

**Issue by h1634668150** [AnzhiZhang/MCDReforgedPlugins#207]
[MCDR] [23:21:08] [commandSpawn/ERROR] [minecraft_data_api]: [Minecraft Data API] Fail to Convert data "name has the following entity data: {seenCredits: 0b, Deat...": Expecting value: line 1 column 19109 (char 19108)
Exception in thread commandSpawn:
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.12/dist-packages/mcdreforged/api/decorator/new_thread.py", line 29, in wrapped_target
    raise e from None
  File "/usr/local/lib/python3.12/dist-packages/mcdreforged/api/decorator/new_thread.py", line 26, in wrapped_target
    self.__return_value = target(*args_, **kwargs_)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins/Bot-v1.1.5.mcdr/bot/command_handler.py", line 449, in __command_spawn
  File "plugins/Bot-v1.1.5.mcdr/bot/bot_manager.py", line 197, in spawn
  File "plugins/Bot-v1.1.5.mcdr/bot/plugin.py", line 102, in get_location

**Comment by AnzhiZhang** [comment]
https://github.com/Fallen-Breath/MinecraftDataAPI/issues/13
