### ISSUE TITLE
[Bot]: fabric1.21.1无法召唤假人

### ISSUE THREAD

**Issue by SkyIce0229** [AnzhiZhang/MCDReforgedPlugins#220]
### Plugin Name | 插件名

Bot-v1.1.5

### Description | 描述

这个是!!bot spawn 之后出现的报错
```log
[MCDR] [15:43:28] [commandSpawn/ERROR] [minecraft_data_api]: [Minecraft Data API] Fail to Convert data "Sky_Ice_ has the following entity data: {seenCredits: 0b, DeathT...": Expecting value: line 1 column 11231 (char 11230)
Exception in thread commandSpawn:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mcdreforged/api/decorator/new_thread.py", line 29, in wrapped_target
    raise e from None
  File "/usr/local/lib/python3.10/dist-packages/mcdreforged/api/decorator/new_thread.py", line 26, in wrapped_target
    self.__return_value = target(*args_, **kwargs_)
  File "plugins/Bot-v1.1.5.mcdr/bot/command_handler.py", line 449, in __command_spawn
  File "plugins/Bot-v1.1.5.mcdr/bot/bot_manager.py", line 197, in spawn
  File "plugins/Bot-v1.1.5.mcdr/bot/plugin.py", line 102, in get_location
TypeError: 'NoneType' object is not subscriptable
```

### Confirmation

- [X] I sincerely confirm that I have searched in previous issues to confirm it is not duplicated, and this should be an issue instead of a discussion.

**Comment by AnzhiZhang** [comment]
Fallen-Breath/MinecraftDataAPI#13

**Comment by SkyIce0229** [comment]
可是我手动把Minecraft Data API V1.5.0替换成V1.6.0并重启后出现这个问题
```log
Exception in thread commandSpawn:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mcdreforged/api/decorator/new_thread.py", line 29, in wrapped_target
    raise e from None
  File "/usr/local/lib/python3.10/dist-packages/mcdreforged/api/decorator/new_thread.py", line 26, in wrapped_target
    self.__return_value = target(*args_, **kwargs_)
  File "plugins/Bot-v1.1.5.mcdr/bot/command_handler.py", line 449, in __command_spawn
  File "plugins/Bot-v1.1.5.mcdr/bot/bot_manager.py", line 197, in spawn
  File "plugins/Bot-v1.1.5.mcdr/bot/plugin.py", line 101, in get_location
AttributeError: module 'minecraft_data_api.entry' has no attribute 'get_player_info'
```
