### ISSUE TITLE
[Bot]: minecraft_data_api 1.6.0: AttributeError: module 'minecraft_data_api.entry' has no attribute 'get_player_info'

### ISSUE THREAD

**Issue by SkyIce0229** [AnzhiZhang/MCDReforgedPlugins#221]
### Plugin Name | 插件名

Bot-v1.1.5

### Description | 描述

```log
Exception in thread commandSpawn:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mcdreforged/api/decorator/new_thread.py", line 29, in wrapped_target
    raise e from None
  File "/usr/local/lib/python3.10/dist-packages/mcdreforged/api/decorator/new_thread.py", line 26, in wrapped_target
    self.__return_value = target(*args_, **kwargs_)
  File "plugins/Bot-v1.1.5.mcdr/bot/command_handler.py", line 449, in __command_spawn
  File "plugins/Bot-v1.1.5.mcdr/bot/bot_manager.py", line 197, in spawn
  File "plugins/Bot-v1.1.5.mcdr/bot/plugin.py", line 101, in get_location
AttributeError: module 'minecraft_data_api.entry' has no attribute 'get_player_info'
```

### Confirmation

- [X] I sincerely confirm that I have searched in previous issues to confirm it is not duplicated, and this should be an issue instead of a discussion.

**Comment by AnzhiZhang** [comment]
你从哪下载的 1.6.0？

**Comment by AnzhiZhang** [comment]
See also: Fallen-Breath/MinecraftDataAPI#16
