### ISSUE TITLE
MCDR安装bot后，加载失败。

### ISSUE THREAD

**Issue by MilkNiuNai** [AnzhiZhang/MCDReforgedPlugins#246]
### Plugin Name | 插件名

bot

### Description | 描述

使用一键安装命令后，重新加载PLG  r bot 出现报错。

### Screenshots丨截图

[MCDR] [11:11:32] [TaskExecutor/ERROR]: Fail to load the entry point of bot@1.2.4
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\mcdreforged\plugin\type\multi_file_plugin.py", line 86, in _on_ready
    self._load_entry_instance()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\mcdreforged\plugin\type\regular_plugin.py", line 79, in _load_entry_instanc
e
    self.entry_module_instance = self._import_entrypoint_module()
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\mcdreforged\plugin\type\multi_file_plugin.py", line 51, in _import_entrypoi
nt_module
    mod = importlib.import_module(self.get_metadata().entrypoint)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "plugins\GUGUbot-v1.8.7.mcdr\gugubot\bot.py", line 18, in <module>
    from .ban_word_system import ban_word_system
ImportError: attempted relative import with no known parent package

### Confirmation

- [X] I sincerely confirm that I have searched in previous issues to confirm it is not duplicated, and this should be an issue instead of a discussion.

**Comment by Redapple-one** [comment]
？为什么没有回答

**Comment by AnzhiZhang** [comment]
不是 bot 的问题

**Comment by Redapple-one** [comment]
OK
