### ISSUE TITLE
[MinedRanking]: 插件加载失败

### ISSUE THREAD

**Issue by Glucy-2** [AnzhiZhang/MCDReforgedPlugins#29]
MCDR v2.3.2
Python v3.9.2
OS: Debian (Linux) 11
```py
[MCDR] [2022-03-23 19:56:06] [TaskExecutor/ERROR]: 插件 SoloPlugin[file=MinedRanking.py,path=plugins/MinedRanking.py,state=PluginState.LOADING] 加载失败
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/mcdreforged/plugin/plugin_manager.py", line 168, in __load_plugin
    plugin.load()
  File "/usr/local/lib/python3.9/dist-packages/mcdreforged/plugin/type/regular_plugin.py", line 93, in load
    self._on_load()
  File "/usr/local/lib/python3.9/dist-packages/mcdreforged/plugin/type/solo_plugin.py", line 47, in _on_load
    self._load_entry_instance()
  File "/usr/local/lib/python3.9/dist-packages/mcdreforged/plugin/type/regular_plugin.py", line 65, in _load_entry_instance
    self.entry_module_instance = self._get_module_instance()
  File "/usr/local/lib/python3.9/dist-packages/mcdreforged/plugin/type/solo_plugin.py", line 39, in _get_module_instance
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "plugins/MinedRanking.py", line 34, in <module>
    class MinedRanking(Thread):
  File "plugins/MinedRanking.py", line 35, in MinedRanking
    def __init__(self, server: ServerInterface, config):
NameError: name 'ServerInterface' is not defined
```

**Comment by zhang-anzhi** [comment]
这是由于MCDR更新接口变化导致的问题，解决方案一：更改MCDR版本，解决方案二：更新插件

**Comment by Glucy-2** [comment]
是直接从仓库下载的最新版插件啊

**Comment by zhang-anzhi** [comment]
> 是直接从仓库下载的最新版插件啊

这个“最新”已经是去年的了，不是你没更新，是我没更新

**Comment by AnzhiZhang** [comment]
该插件已归档，不再更新

---

如果您愿意维护，乐意接受PR，或在遵守 [GNU General Public License v3.0](https://github.com/AnzhiZhang/MCDReforgedPlugins/blob/master/LICENSE) 协议的前提下自行更新维护
该协议的要点包括但不限于以下内容（全部内容请自行阅读）：修改后的内容必须以相同协议开源，禁止闭源，您也必须标注来源
