### ISSUE TITLE
[QQChat]: 无法加载插件

### ISSUE THREAD

**Issue by RedBeanhgd** [AnzhiZhang/MCDReforgedPlugins#30]
Error invoking listener EventListener[plugin=qq_chat@0.0.3,priority=1000,callback=<function on_load at 0x00000210DE1AAC20>]
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\mcdreforged\plugin\plugin_manager.py", line 474, in trigger_listener
    listener.execute(listener.plugin.server_interface, *args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\mcdreforged\plugin\plugin_event.py", line 79, in execute
    return self.callback(*args, **kwargs)
  File "F:\rb\mcdr\plugins\QQChat.py", line 62, in on_load
    from ConfigAPI.py import Config
ModuleNotFoundError: No module named 'ConfigAPI'

**Comment by AnzhiZhang** [comment]
插件还没跟着MCDR更新，或者可以自行装上ConfigAPI

**Comment by AnzhiZhang** [comment]
已支持 MCDR2.0，请查看最新版下载
